<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\**" />
    <Compile Remove="Interfaces\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <None Remove="Exceptions\**" />
    <None Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exeptions\" />
  </ItemGroup>

</Project>
